Geekium/Models/Account.cs
using System;
using System.Collections.Generic;

// Code scaffolded by EF Core assumes nullable reference types (NRTs) are not used or disabled.
// If you have enabled NRTs for your project, then un-comment the following line:
// #nullable disable

namespace Geekium.Models
{
    public partial class Account
    {
        public Account()
        {
            AccountPurchases = new HashSet<AccountPurchase>();
            Cart = new HashSet<Cart>();
            Rewards = new HashSet<Reward>();
            SellerAccounts = new HashSet<SellerAccount>();
            SellerReviews = new HashSet<SellerReview>();
            ServiceListings = new HashSet<ServiceListing>();
        }

        public int AccountId { get; set; }
        public string UserName { get; set; }
        public string UserPassword { get; set; }
        public string PaswordHash { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public int? PointBalance { get; set; }

        public virtual ICollection<AccountPurchase> AccountPurchases { get; set; }
        public virtual ICollection<Cart> Cart { get; set; }
        public virtual ICollection<Reward> Rewards { get; set; }
        public virtual ICollection<SellerAccount> SellerAccounts { get; set; }
        public virtual ICollection<ServiceListing> ServiceListings { get; set; }
        public virtual ICollection<SellerReview> SellerReviews { get; set; }
    }
}

Geekium/Models/AccountViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Geekium.Models
{
	public class AccountViewModel
	{
		[Required]
		[StringLength(50, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long", MinimumLength = 6)]
		public string Username { get; set; }

		[Required]
		[StringLength(50, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long", MinimumLength = 6)]
		[DataType(DataType.Password)]
		[Display(Name = "Password")]
		public string Password { get; set; }

		[Required]
		[StringLength(50, ErrorMessage = "The First Name must be less than {1}")] 
		public string FirstName { get; set; }

		[Required]
		[StringLength(50, ErrorMessage = "The First Name must be less than {1}")]
		public string LastName { get; set; }
		
		[Required]
		[EmailAddress]
		[Display(Name = "Email")]
		public string Email { get; set; }

		public string ReturnUrl { get; set; }
	}
}

Geekium/Models/LoginViewModel.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Geekium.Models
{
	public class LoginViewModel
	{
		[Required]
		public string Username { get; set; }

		[Required]
		[DataType(DataType.Password)]
		public string Password { get; set; }

		public string ReturnUrl { get; set; }
	}
}

Geekium/Models/UpgradeViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Geekium.Models
{
	public class UpgradeViewModel
	{
		[Required]
		[StringLength(6, ErrorMessage = "The code cannot be greater than {1}")]
		public string Code { get; set; }

		public string ReturnUrl { get; set; }
	}
}

Geekium/Controllers/AccountsController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Geekium.Models;
using Microsoft.AspNetCore.Http;
using System.Security.Cryptography;
using System.Text;
using System.IO;
using System.Net.Mail;
using System.Net;
using Microsoft.AspNetCore.Hosting;

namespace Geekium.Controllers
{
    public class AccountsController : Controller
    {
        private readonly GeekiumContext _context;
        private readonly IWebHostEnvironment _hostEnvironment;

        private static Random random = new Random();

        public AccountsController(GeekiumContext context, IWebHostEnvironment hostEnvironment)
        {
            _context = context;
            _hostEnvironment = hostEnvironment;
        }

        // GET: Accounts
        public async Task<IActionResult> Index()
        {
            return View();
        }

        // GET: Accounts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var account = await _context.Accounts
                .FirstOrDefaultAsync(m => m.AccountId == id);
            if (account == null)
            {
                return NotFound();
            }

            return View(account);
        }

        [HttpGet]
        public IActionResult Create(string returnUrl = "")
        {
            var model = new AccountViewModel { ReturnUrl = returnUrl };
            return View(model);
        }

        //Will retrieve the AccountViewModel data given by the user, check if the supplied user name and email are already taken,
        //create a new account object with that data, add that account object to the database, 
        //and perform a login with the supplied username and password
        [HttpPost]
        public async Task<IActionResult> Create(AccountViewModel model)
        {
            if (ModelState.IsValid)
            {
                foreach (var dbItem in _context.Accounts)
                {
                    if (dbItem.UserName == model.Username)
                    {
                        ModelState.AddModelError("", "Username already taken");
                        return View(model);
                    }
                    else if (dbItem.Email == model.Email)
					{
                        ModelState.AddModelError("", "Email already taken");
                        return View(model);
                    }
                }

                var originalPassword = model.Password;
                string key = RandomString();

                var encryptedPassword = EncryptString(originalPassword, key);

                Account account = new Account();
                account.UserName = model.Username;
                account.UserPassword = encryptedPassword.ToString();
                account.PaswordHash = key.ToString();
                account.FirstName = model.FirstName;
                account.LastName = model.LastName;
                account.Email = model.Email;
                account.PointBalance = 0;
                

                _context.Add(account);
                await _context.SaveChangesAsync();

                LoginViewModel loginModel = new LoginViewModel();
                loginModel.Username = model.Username;
                loginModel.Password = model.Password;

                await Login(loginModel);
                return RedirectToAction("Index", "Home");
            }
            ModelState.AddModelError("", "Invalid attempt");
            return View(model);
        }

        //Will retrieve the Login screen for the user and set the returnUrl accordingly so that the user is directed back to the
        //same page in the event that the login attempt has failed
        [HttpGet]
        public IActionResult Login(string returnUrl = "")
        {
            var model = new LoginViewModel { ReturnUrl = returnUrl };
            return View(model);
        }

        //Will retrieve the LoginViewModel data given by the user, check that the data corresponds with an existing account on the
        //database, create session objects for the account username and id, and direct the user to the Home page
        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel model)
        {
            if (ModelState.IsValid)
            {
                var account = await _context.Accounts.FirstOrDefaultAsync(m => m.UserName == model.Username);
                if (account != null)
				{
					var decryptedPassword = DecryptString(account.UserPassword, account.PaswordHash);

					if (decryptedPassword == model.Password)
					{
						HttpContext.Session.SetString("username", account.UserName);
						HttpContext.Session.SetString("userId", account.AccountId.ToString());
                        HttpContext.Session.SetString("userEmail", account.Email);
                        if(account.PointBalance == null)
						{
                            account.PointBalance = 0;
                            HttpContext.Session.SetInt32("pointsBalance", 0);
                        }
                        else
						{
                            HttpContext.Session.SetInt32("pointsBalance", (int)account.PointBalance);
                        }
                        
                        var sellerAccount = await _context.SellerAccounts.FirstOrDefaultAsync(m => m.AccountId == account.AccountId);
						if (sellerAccount != null)
						{
                            HttpContext.Session.SetInt32("sellerId", sellerAccount.SellerId);
                        }

						return RedirectToAction("Index", "Home");
					}
				}
            }
            ModelState.AddModelError("", "Invalid attempt");
            return View(model);
        }

        //Will clear all session variables and return the user to the Home screen
        public async Task<IActionResult> Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Index", "Home");
        }

        //Will direct user to the Upgrade page and set the returnUrl variable if an error has occured
        [HttpGet]
        public IActionResult Upgrade(string returnUrl = "")
        {
            SendEmail();

			var model = new UpgradeViewModel { ReturnUrl = returnUrl };
            return View(model);
        }

        //Will check if the code sent by email matches the code generated in the application, and will create a new SellerAccount
        //object using the account credidentials
        [HttpPost]
        public async Task<IActionResult> Upgrade(UpgradeViewModel model)
        {
            if(ModelState.IsValid)
			{
                if (model.Code == HttpContext.Session.GetString("emailCode"))
                {
                    SellerAccount sellerAccount = new SellerAccount();
                    sellerAccount.AccountId = Int32.Parse(HttpContext.Session.GetString("userId"));
                    HttpContext.Session.SetInt32("sellerId", sellerAccount.SellerId);

                    SellerAccountsController sellerAccountsController = new SellerAccountsController(_context, _hostEnvironment);
                    await sellerAccountsController.Create(sellerAccount);

                    return View("UpgradeSuccess");
                }
                ModelState.AddModelError("", "Code is invalid");
            }
            ModelState.AddModelError("", "Invalid Attempt");
            return View(model);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var account = await _context.Accounts.FindAsync(id);
            if (account == null)
            {
                return NotFound();
            }
            return View(account);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("AccountId,UserName,UserPassword,PaswordHash,FirstName,LastName,Email,PointBalance")] Account account)
        {
            if (id != account.AccountId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(account);
                    await _context.SaveChangesAsync();

                    //Set Session objects for the User Name to be used throughout the web application
                    HttpContext.Session.SetString("username", account.UserName);
                    HttpContext.Session.SetString("userEmail", account.Email);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AccountExists(account.AccountId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index", "Home");
            }
            return View(account);
        }

        //Will edit exising account object by adding new point balance to the account
        public async Task<IActionResult> EditPoints(Account account, int pointBalance)
        {
            if (account == null)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                account.PointBalance = pointBalance;

                _context.Update(account);
                await _context.SaveChangesAsync();

                return RedirectToAction("Index", "Home");
            }
            return View(account);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var account = await _context.Accounts
                .Include(g => g.SellerAccounts)

Geekium/Views/Accounts/Create.cshtml
@model AccountViewModel
@{
	ViewBag.Title = "Create";
}
<h4>Please enter your account details below:</h4>

<div class="row">
	<div class="col-md-4">
		<form method="post" asp-controller="Accounts" asp-action="Create" asp-route-returnurl="@Model.ReturnUrl">
			<div class="form-group">
				<label asp-for="Username" class="control-label">Username:</label>
				<input asp-for="Username" class="form-control" />
			</div>
			<div class="form-group">
				<label asp-for="Password" class="control-label">Password:</label>
				<input asp-for="Password" class="form-control" />
			</div>
			<div class="form-group">
				<label asp-for="FirstName" class="control-label">First Name:</label>
				<input asp-for="FirstName" class="form-control" />
			</div>
			<div class="form-group">
				<label asp-for="LastName" class="control-label">Last Name:</label>
				<input asp-for="LastName" class="form-control" />
			</div>
			<div class="form-group">
				<label asp-for="Email" class="control-label">Email:</label>
				<input asp-for="Email" class="form-control" />
			</div>
			<div class="text-danger">
				@Html.ValidationSummary()
			</div>
			<input type="submit" value="Create" />
		</form>
	</div>
</div>   

Geekium/Views/Accounts/Delete.cshtml
@using Microsoft.AspNetCore.Http
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor
@model Geekium.Models.Account

@{
	ViewData["Title"] = "Delete";
}

<h4>Are you sure you wish to delete your account?</h4>
<p>This action cannot be undone!</p>
<div>
	<hr />
	<dl class="row">
		<dt class="col-sm-2">Username:</dt>
		<dd class="col-sm-10">@Html.DisplayFor(model => model.UserName)</dd>
	</dl>

	<form asp-action="Delete">
		<input type="hidden" asp-for="AccountId" />
		<input type="submit" value="Delete" class="btn btn-danger" />
		<a asp-area="" asp-controller="Accounts" asp-action="Details" asp-route-id="@HttpContextAccessor.HttpContext.Session.GetString("userId")" class="btn btn-info">Cancel</a>
	</form>
</div>

Geekium/Views/Accounts/Details.cshtml
@model Geekium.Models.Account
@using Microsoft.AspNetCore.Http
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor

@{
	ViewData["Title"] = "Details";
}

<div style="align-content: center; align-items: center;">
	<div class="form-inline">
		<a class="btn btn-outline-info form-control col-md-4" role="button" asp-action="Edit" asp-route-id="@HttpContextAccessor.HttpContext.Session.GetString("userId")">Edit Account</a>

		@if (HttpContextAccessor.HttpContext.Session.GetString("sellerId") == null)
		{
			<a class="btn btn-outline-info form-control col-md-4" role="button" asp-action="Upgrade" asp-route-id="@HttpContextAccessor.HttpContext.Session.GetString("userId")">Upgrade to Seller</a>
		}

		<a class="btn btn-outline-info form-control col-md-4" role="button" asp-action="Delete" asp-route-id="@HttpContextAccessor.HttpContext.Session.GetString("userId")">Delete Account</a>
	</div>
</div>

<br />

@if (HttpContextAccessor.HttpContext.Session.GetString("sellerId") != null)
{
	<h4>Seller Account</h4>
}
else
{
	<h4>Buyer Account</h4>
}

<hr />

<div>
	<p>Your Account Details</p>
	<dl class="row">
		<dt class="col-sm-2">
			Username:
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.UserName)
		</dd>
		<dt class="col-sm-2">
			First Name:
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.FirstName)
		</dd>
		<dt class="col-sm-2">
			Last Name:
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.LastName)
		</dd>
		<dt class="col-sm-2">
			Email Address:
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.Email)
		</dd>
		<dt class="col-sm-2">
			Point Balance:
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.PointBalance)
		</dd>
	</dl>
</div>

Geekium/Views/Accounts/Edit.cshtml
@model Geekium.Models.Account
@using Microsoft.AspNetCore.Http
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor

@{
	ViewData["Title"] = "Edit";
}

<h4>Please enter your updated account details below:</h4>
<p>Only your username and email will be displayed on the website for other users</p>
<hr />
<div class="row">
	<div class="col-md-4">
		<form asp-action="Edit">
			<div asp-validation-summary="ModelOnly" class="text-danger"></div>
			<input type="hidden" asp-for="AccountId" />
			<div class="form-group" hidden>
				<label asp-for="PointBalance" class="control-label"></label>
				<input asp-for="PointBalance" class="form-control" />
				<span asp-validation-for="PointBalance" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="UserName" class="control-label"></label>
				<input asp-for="UserName" class="form-control" />
				<span asp-validation-for="UserName" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="FirstName" class="control-label"></label>
				<input asp-for="FirstName" class="form-control" />
				<span asp-validation-for="FirstName" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="LastName" class="control-label"></label>
				<input asp-for="LastName" class="form-control" />
				<span asp-validation-for="LastName" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Email" class="control-label"></label>
				<input asp-for="Email" class="form-control" />
				<span asp-validation-for="Email" class="text-danger"></span>
			</div>
			<div class="form-group" hidden>
				<label asp-for="UserPassword" class="control-label"></label>
				<input asp-for="UserPassword" class="form-control" />
				<span asp-validation-for="UserPassword" class="text-danger"></span>
			</div>
			<div class="form-group" hidden>
				<label asp-for="PaswordHash" class="control-label"></label>
				<input asp-for="PaswordHash" class="form-control" />
				<span asp-validation-for="PaswordHash" class="text-danger"></span>
			</div>
			<div class="form-group">
				<input type="submit" value="Save" class="btn btn-primary" />
				<a asp-action="Delete" asp-route-id="@HttpContextAccessor.HttpContext.Session.GetString("userId")" class="btn btn-danger">Delete</a>
				<a asp-action="Details" asp-route-id="@HttpContextAccessor.HttpContext.Session.GetString("userId")" class="btn btn-info">Cancel</a>
			</div>
		</form>
	</div>
</div>

@section Scripts {
	@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Geekium/Views/Accounts/Index.cshtml
@model Geekium.Models.Account
@using Microsoft.AspNetCore.Http
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor

<h1>Manage your account</h1>

<div>
	<ul class="">
		<li><a class="btn" asp-area="" asp-controller="Accounts" asp-action="Edit" asp-route-id="@HttpContextAccessor.HttpContext.Session.GetString("userId")">Account Details</a></li>
		<li><a class="btn" asp-area="" asp-controller="Accounts" asp-action="Upgrade" asp-route-id="@HttpContextAccessor.HttpContext.Session.GetString("userId")">Upgrade to Seller</a></li>
		<li><a class="btn" asp-area="" asp-controller="Accounts" asp-action="Delete" asp-route-id="@HttpContextAccessor.HttpContext.Session.GetString("userId")">Delete Account</a></li>
	</ul>
</div>
<br />
<hr />
<div style="width:50%;text-align:center">
	<dl class="row">
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.UserName)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.UserName)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.UserPassword)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.UserPassword)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.FirstName)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.FirstName)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.LastName)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.LastName)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.Email)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.Email)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.PointBalance)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.PointBalance)
		</dd>
	</dl>
</div>

Geekium/Views/Accounts/Login.cshtml
@model LoginViewModel
@{
	ViewBag.Title = "Login";
}
<h4>Please login with your details below:</h4>

<div class="row">
	<div class="col-md-4">
		<form method="post" asp-controller="Accounts" asp-action="Login" asp-route-returnurl="@Model.ReturnUrl">
			<div class="form-group">
				<label asp-for="Username" class="control-label">Username:</label>
				<input asp-for="Username" class="form-control" />
			</div>
			<div class="form-group">
				<label asp-for="Password" class="control-label">Password:</label>
				<input asp-for="Password" class="form-control" />
			</div>
			<div class="text-danger">
				@Html.ValidationSummary()
			</div>
			<input type="submit" value="Login" />
		</form>
		<br />
		<p>Don't have an account? <a asp-area="" asp-controller="Accounts" asp-action="Create">Register</a>
		</p>
	</div>
</div>     

Geekium/Views/Accounts/Upgrade.cshtml
@model UpgradeViewModel
@using Microsoft.AspNetCore.Http
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor
@{
	ViewData["Title"] = "Upgrade";
}

<h4>A 6 digit one time use code has been emailed to you for authentication purposes, please enter it below:</h4>
<hr />
<div class="row">
	<div class="col-md-4">
		<form method="post" asp-controller="Accounts" asp-action="Upgrade" asp-route-returnurl="@Model.ReturnUrl">
			<div class="form-group">
				<label asp-for="Code" class="control-label">Code:</label>
				<input asp-for="Code" class="form-control" />
			</div>
			<div class="text-danger">
				@Html.ValidationSummary()
			</div>
			<div class="form-group">
				<input type="submit" value="Upgrade" class="btn btn-primary" />
				<a asp-action="Upgrade" asp-route-id="@HttpContextAccessor.HttpContext.Session.GetString("userId")" class="btn btn-secondary">Resend Code</a>
				<a asp-action="Details" asp-route-id="@HttpContextAccessor.HttpContext.Session.GetString("userId")" class="btn btn-info">Cancel</a>
			</div>
		</form>
	</div>
</div>

Geekium/Views/Accounts/UpgradeSuccess.cshtml
@using Microsoft.AspNetCore.Http
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor
@{
	ViewData["Title"] = "Upgrade Success";
}

<h4>Your account has been successfully upgraded to a seller account!</h4>
<hr />
<p>You can begin selling items <a asp-area="" asp-controller="MyListings" asp-action="Index">here</a></p>