Geekium/Models/Cart.cs
using System;
using System.Collections.Generic;

// Code scaffolded by EF Core assumes nullable reference types (NRTs) are not used or disabled.
// If you have enabled NRTs for your project, then un-comment the following line:
// #nullable disable

namespace Geekium.Models
{
    public partial class Cart
    {
        public Cart()
        {
            AccountPurchases = new HashSet<AccountPurchase>();
            ItemsForCart = new HashSet<ItemsForCart>();
            Receipt = new HashSet<Receipt>();
        }

        public int CartId { get; set; }
        public int AccountId { get; set; }
        public bool? TransactionComplete { get; set; }
        public int? NumberOfProducts { get; set; }
        public double? TotalPrice { get; set; }
        public int? PointsGained { get; set; }

        public virtual Account Account { get; set; }
        public virtual ICollection<AccountPurchase> AccountPurchases { get; set; }
        public virtual ICollection<ItemsForCart> ItemsForCart { get; set; }
        public virtual ICollection<Receipt> Receipt { get; set; }
    }
}

Geekium/Controllers/CartsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Geekium.Models;
using Microsoft.AspNetCore.Http;
using Geekium.Helpers;
using Stripe;
using System.Net.Mail;
using System.Net;
using System.Text;
using Microsoft.AspNetCore.Hosting;

namespace Geekium.Controllers
{
    public class CartsController : Controller
    {
        private readonly GeekiumContext _context;
        private long stripePay;
        private readonly IWebHostEnvironment _hostEnvironment;

        public CartsController(GeekiumContext context, IWebHostEnvironment hostEnvironment)
        {
            _context = context;
            _hostEnvironment = hostEnvironment;
        }

        // Get contents of cart and return index page
        public async Task<IActionResult> Index()
        {
            string accountId = HttpContext.Session.GetString("userId"); 
            string url = "/Accounts/Login";
            if(accountId == null)
            {
                return LocalRedirect(url);
            }
            else
            {
                // Find the cart associated with this account
                var cartContext = await _context.Cart
                    .Include(c => c.Account)
                    .Where(s => s.TransactionComplete == false)
                    .FirstOrDefaultAsync(s => s.AccountId.ToString() == accountId);

                // If the account does not have a cart associated with them, create one
                if (cartContext == null)
				{
                    await CreateCart(accountId);
                    cartContext = await _context.Cart
                        .Where(s => s.TransactionComplete == false)
                        .FirstOrDefaultAsync(s => s.AccountId.ToString() == accountId);

                    // Calculate subtotal
                    double total = 0; // This is not updating properly
                    ViewBag.subTotal = total;
                    stripePay = 0;

                    // Calculate points
                    string points = PointsEarned(total).ToString();
                    ViewBag.points = PointsEarned(ViewBag.subTotal);

                    return View();
                }
                else
				{
                    // Find all the items associated with this cart
                    var cartItems = await _context.ItemsForCart
                        .Include(s => s.SellListing)
                        .Include(s => s.Cart)
                        .Where(s => s.SellListingId == s.SellListing.SellListingId)
                        .Where(s => s.CartId == cartContext.CartId)
                        .ToListAsync();

                    if (cartItems.Count != 0)
                    {
                        foreach (var item in cartItems)
                        {
                            if (item.Quantity > item.SellListing.SellQuantity)
                                item.Quantity = item.SellListing.SellQuantity;
                        }
                    }

                    // Calculate subtotal
                    double total = SubTotal(cartItems); // This is not updating properly
                    ViewBag.subTotal = total;
                    stripePay = (long)SubTotal(cartItems);

                    // Calculate points
                    string points = PointsEarned(total).ToString();
                    ViewBag.points = PointsEarned(ViewBag.subTotal);

                    return View(cartItems);
                }
            }
        }

        #region Cart Functions
        // Creates the cart
        public async Task<IActionResult> CreateCart(string id)
        {
            string userId = id;
            Cart cart = new Cart();
            cart.AccountId = int.Parse(userId);
            cart.TransactionComplete = false;
            cart.NumberOfProducts = 0;
            cart.TotalPrice = 0;
            cart.PointsGained = 0;

            if (ModelState.IsValid)
            {
                _context.Add(cart);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            
            return RedirectToAction("Index");
        }

        // Check if cart exists
        private bool CartExists(int id)
        {
            return _context.Cart.Any(e => e.CartId == id);
        }

        // Removing item from cart
        public async Task<IActionResult> Remove(int id)
        {
            // Find the corresponding item to remove from cart
            var itemToRemove = await _context.ItemsForCart.FindAsync(id);
            _context.ItemsForCart.Remove(itemToRemove);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        // Adding the item to cart
        public async Task<IActionResult> Add(int listingId, string userId)
        {
            string url = "/Accounts/Login";
            if (userId == null)
            {
                return LocalRedirect(url);
            }


            // Find the cart associated with this account
            var cartContext = await _context.Cart
                .Where(s => s.TransactionComplete == false)
                .FirstOrDefaultAsync(s => s.AccountId.ToString() == userId);

            // If the account does not have a cart associated with them, create one
            if (cartContext == null)
            {
                await CreateCart(userId);
                cartContext = await _context.Cart.
                    Where(s => s.TransactionComplete == false)
                    .FirstOrDefaultAsync(s => s.AccountId.ToString() == userId);
            }

            // Does this item already exist in this cart?
            var itemContext = await _context.ItemsForCart
                .Where(s => s.CartId == cartContext.CartId)
                .FirstOrDefaultAsync(s => s.SellListingId == listingId);

            if (itemContext == null)
            {
                ItemsForCart item = new ItemsForCart();
                item.CartId = cartContext.CartId;
                item.SellListingId = listingId;
                item.Quantity = 1;

                if (ModelState.IsValid)
                {
                    _context.Add(item);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
            }
            else
            {
                // Find the associated cart item
                itemContext.Quantity++;
                _context.Update(itemContext);
                await _context.SaveChangesAsync();
            }

            return RedirectToAction("Index");
        }

        // Updating quantity of item from cart page
        public async Task<IActionResult> UpdateQuantity(int id, int quantity)
        {
            string accountId = HttpContext.Session.GetString("userId");
            string url = "/Accounts/Login";
            if (accountId == null)
            {
                return LocalRedirect(url);
            }

            // Find the cart associated with this account
            var cartContext = await _context.Cart
                .Where(s => s.TransactionComplete == false)
                .FirstOrDefaultAsync(s => s.AccountId.ToString() == accountId);

            // Find the associated cart item
            var itemContext = await _context.ItemsForCart
                .Include(s => s.SellListing)
                .Where(s => s.CartId == cartContext.CartId)
                .FirstOrDefaultAsync(s => s.ItemsForCartId == id);

            if (ModelState.IsValid)
            {
                try
                {
                    if (!(quantity > itemContext.SellListing.SellQuantity))
                    {
                        itemContext.Quantity = quantity;
                        _context.Update(itemContext);
                        await _context.SaveChangesAsync();
                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    // I probably should do this for itemforcart instead of cart itself
                    if (!CartExists(cartContext.CartId))
                        return NotFound();
                    else
                        throw;
                }

                return RedirectToAction("Index");
            }

            return RedirectToAction("Index");
        }

        //Update current cart item and set TransactionComplete to "true"
        public async Task ChangeCartTransactionStatus([Bind("CartId,AccountId,TransactionComplete,NumberOfProducts,TotalPrice,PointsGained")] Cart cart)
		{
            if (ModelState.IsValid)
            {
                cart.TransactionComplete = true;
                _context.Update(cart);
                await _context.SaveChangesAsync();
            }
        }

        //Delete any cart objects and items for cart objects from the database, to be used when the account is deleted
        public async Task<IActionResult> DeleteCart(int id)
        {
            var cart = await _context.Cart.FindAsync(id);

            var itemContext = await _context.ItemsForCart
                .Where(s => s.CartId == cart.CartId)
                .ToListAsync();

            foreach(var item in itemContext)
			{
                _context.ItemsForCart.Remove(item);
                await _context.SaveChangesAsync();
            }

            _context.Cart.Remove(cart);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        #endregion

        #region Checkout Functions
        //Payment page
        public async Task<IActionResult> CartPayment()
        {
            // Find the cart associated with this account
            var cartContext = await _context.Cart
                .Where(s => s.TransactionComplete == false)

Geekium/Views/Carts/CartPayment.cshtml
@using Microsoft.Extensions.Options
@using Microsoft.AspNetCore.Http
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor
@inject IOptions<Geekium.Data.StripeSettings> Stripe
@{
    ViewData["Title"] = "CartPayment";
}
<!DOCTYPE html>
<div class="text-center">
    <h1 class="display-4">Cart Checkout</h1>
</div>

<div class="text-center">
    <p>Sub Total: $@ViewBag.subTotal.ToString("#0.00")</p>
    <p>Tax: $@ViewBag.tax.ToString("#0.00")</p>
    <form asp-action="CheckOut" asp-controller="Carts" method="POST">
        <article>
            <label>Sum: $@ViewBag.total.ToString("#0.00")</label>
        </article>
        <script src="//checkout.stripe.com/v2/checkout.js"
                class="stripe-button"
                data-key="@Stripe.Value.PublishableKey"
                data-locale="auto"
                data-description="Product Checkout"
                data-amount="@ViewBag.totalStripe"
                data-currency="cad">
        </script>
    </form>
</div>

Geekium/Views/Carts/Index.cshtml
@model IEnumerable<Geekium.Models.ItemsForCart>
@using Microsoft.Extensions.Options
@inject IOptions<Geekium.Data.StripeSettings> Stripe
@using Microsoft.AspNetCore.Http
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor
@{
	ViewData["Title"] = "Index";
}
<div class="text-center">
	<h1 class="display-4">Cart</h1>
</div>

<body onload="recalculateSubtotal(null)">
	@if (Model == null)
	{
		<h4 style="text-align:center">Your cart seems to be empty!</h4>
	}
	else
	{
		@if (Model.Count() > 0)
		{
			<table class="table">
				<tr>
					<th>Product</th>
					<th>Images appear below</th>
					<th>Description</th>
					<th>Price</th>
					<th>Quantity</th>
					<th></th>
				</tr>
				@{ var count = 0; }
				@foreach (var item in Model)
				{
					<tr>
						<td class="truncate">@Html.DisplayFor(modelItem => item.SellListing.SellTitle)</td>
						<td><img class="displayImage" src="@("~/images/"+item.SellListing.SellImage)" asp-append-version="true" width="250" height="250" /></td>
						<td class="truncate">@Html.DisplayFor(modelItem => item.SellListing.SellDescription)</td>
						<td>$@Html.DisplayFor(modelItem => item.SellListing.SellPrice) </td>
						<td>
							<input id="quantity(@count)" onchange="recalculateSubtotal(@item.ItemsForCartId, this.id)" type="number" max="999" min="1" value="@Html.DisplayFor(modelItem => item.Quantity)" />
						</td>
						<td><a asp-controller="Carts" asp-action="Remove" asp-route-id="@item.ItemsForCartId">Remove Item</a></td>
					</tr>
					count++;
				}
				<tr>
					<td align="right" colspan="4">Subtotal</td>
					<td>$@ViewBag.subTotal.ToString("#0.00")</td>
				</tr>
			</table>
			}
			else
			{
			<h4 style="text-align:center">Your cart seems to be empty!</h4>
			}
		<a class="btn btn-success" role="button" asp-area="" asp-controller="Carts" asp-action="CartPayment" style="float: right;">Proceed to Checkout</a>
		<a class="btn btn-primary" role="button" asp-controller="SellListings" asp-action="Index">Continue Shopping</a>

		@if (@HttpContextAccessor.HttpContext.Session.GetString("rewardType") != null)
		{
			<div class="text-center">
				<p>Your discount code for @HttpContextAccessor.HttpContext.Session.GetString("rewardType") has been applied</p>
			</div>	
		}
	}
</body>

<script>
	function recalculateSubtotal(id, inputId) {
		console.log(id);
		console.log(inputId);

		if (id != null) {

			var y = document.getElementById(inputId).value;
			if (y < 0) {
				y = 0
				document.getElementById(inputId).value = 0;
			}
			else if (y > 999) {
				y = 999
				document.getElementById(inputId).value = 999;
			}

			UpdateCart(id, y);
		}
	}
    function UpdateCart(id, quantity) {
        $.ajax({
            url: 'Carts/UpdateQuantity',
            data: { id: id, quantity: quantity },
            success: function () {
                window.location.reload();
            }
        });
    }
</script>